In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("crypto_database.db")

In [3]:
csv_files = {
    "ETH": "raw/ETH_price_data.csv",
    "XRP": "raw/XRP_price_data.csv",
    "LTC": "raw/LTC_price_data.csv",
    "ADA": "raw/ADA_price_data.csv",
    "DOT": "raw/DOT_price_data.csv",
    "LINK": "raw/LINK_price_data.csv",
    "BNB": "raw/BNB_price_data.csv",
    "UNI": "raw/UNI_price_data.csv",
    "DOGE": "raw/DOGE_price_data.csv"
}

In [29]:
tickers = list(csv_files.keys())

for ticker in tickers:
    if ticker != 'BTC':
        query = f"""
        SELECT b.time,
               b.open as BTC_open,
               b.close as BTC_close,
               b.volumeto as BTC_volume,
               {ticker}.open as {ticker}_open,
               {ticker}.close as {ticker}_close,
               {ticker}.volumeto as {ticker}_volume
        FROM BTC as b
        INNER JOIN {ticker} as {ticker}
        ON b.time = {ticker}.time
        """
        df_dict[ticker] = pd.read_sql(query, conn)

In [48]:
for i in range(len(list(df_dict.values()))):
    list(df_dict.values())[i].to_csv(f'merged_data/{list(csv_files.keys())[i]}')

In [4]:
symbols = list(csv_files.keys())

# Base query with just BTC
query = f"""
SELECT b.time,
       b.open as BTC_open,
       b.close as BTC_close,
       b.volumeto as BTC_volume
"""

# Add the columns for each table to the SELECT statement and add the necessary JOIN statements
for symbol in symbols:
    if symbol != 'BTC': # since we have already included BTC
        query += f""",
               {symbol}.open as {symbol}_open,
               {symbol}.close as {symbol}_close,
               {symbol}.volumeto as {symbol}_volume"""

query += "\nFROM BTC as b"

for symbol in symbols:
    if symbol != 'BTC': # since we have already included BTC
        query += f"""
        INNER JOIN {symbol} as {symbol}
        ON b.time = {symbol}.time"""

# Execute the query
df = pd.read_sql(query, conn)

In [5]:
df.to_csv('')

,time,BTC_open,BTC_close,BTC_volume,ETH_open,ETH_close,ETH_volume,XRP_open,XRP_close,XRP_volume,...,LINK_volume,BNB_open,BNB_close,BNB_volume,UNI_open,UNI_close,UNI_volume,DOGE_open,DOGE_close,DOGE_volume
0,2016-12-10 03:00:00,774.14,773.22,300299.79,8.534,8.497,51562.17,0.006890,0.006835,4.121820e+03,...,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.000217,0.000209,69.81
1,2016-12-10 04:00:00,773.22,774.38,445496.69,8.451,8.472,50452.13,0.006950,0.006950,1.000000e-01,...,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.000209,0.000217,449.30
2,2016-12-10 05:00:00,774.38,772.83,531621.78,8.472,8.486,37777.28,0.006945,0.006812,2.429000e+00,...,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.000217,0.000216,1505.58
3,2016-12-10 06:00:00,772.83,774.44,361825.55,8.482,8.624,27672.78,0.006820,0.006820,1.745000e+00,...,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.000216,0.000217,19.10
4,2016-12-10 07:00:00,774.44,770.87,334746.86,8.457,8.402,63425.22,0.006820,0.006942,9.177000e-02,...,0.00,0.00,0.00,0.00,0.000,0.000,0.00,0.000217,0.000216,353.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86640,2023-07-23 15:00:00,29898.46,29902.34,4229015.95,1873.120,1873.990,4892939.49,0.740500,0.740300,1.388897e+06,...,326043.13,242.40,242.21,176049.16,6.117,6.107,25510.08,0.072270,0.071990,285640.21
86641,2023-07-23 16:00:00,29902.34,29955.25,12797731.71,1873.990,1883.670,12064390.00,0.740300,0.742600,1.301313e+06,...,404233.36,242.21,242.99,159208.49,6.107,6.151,59140.50,0.071990,0.072320,572696.70
86642,2023-07-23 17:00:00,29955.25,30121.03,22541052.08,1883.670,1894.190,9373882.58,0.742600,0.748500,1.409329e+06,...,905321.57,242.99,243.69,219805.01,6.151,6.188,221212.21,0.072320,0.072720,801134.51
86643,2023-07-23 18:00:00,30121.03,30255.16,30654325.30,1894.190,1902.040,14327879.24,0.748500,0.747800,1.029641e+06,...,636732.53,243.65,243.34,529600.34,6.188,6.194,82128.27,0.072720,0.072790,740971.85
86644,2023-07-23 19:00:00,30255.16,30090.59,35575032.62,1902.040,1888.990,15511999.76,0.747800,0.738100,2.771561e+06,...,806678.31,243.34,242.50,330743.41,6.194,6.163,308531.73,0.072790,0.071910,1196675.04